language: python
services:
  - docker

env:
  - DOCKER_REPO_SLUG=da3thni3ox/ui

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

jobs:
  include:
    - stage: Build
      name: Build image
      script:
        - docker build -t $DOCKER_REPO_SLUG:latest .

after_success:
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH = master ]]; then docker push $DOCKER_REPO_SLUG:latest; else true; fi


