language: python
services:
  - docker

env:
  - DOCKER_REPO=da3thni3ox

jobs:
  include:
    - stage: Build
      name: Build image
      script:
        - docker build -t $DOCKER_REPO/ui:latest

after_success:
  - if [[ $TRAVIS_BRANCH = master ]]; then docker push $DOCKER_REPO/ui:latest; else true; fi


